enum Inspector 
{
    static 
    let entrypoint:String = "__inspector_entrypoint_loader__"
}

#if !BUILD_STAGE_INERT 

import TSCBasic
import Workspace

extension Inspector 
{
    static 
    func inspect(workspace:AbsolutePath, toolchain:AbsolutePath, 
        dependency:(package:String, product:String, path:AbsolutePath)) throws
        -> [(typename:String, symbols:[String], signatures:[String])]
    {
        typealias InspectorFunction = () -> [(typename:String, symbols:[String], signatures:[String])]
        
        let triple:Triple = .getHostTriple(usingSwiftCompiler: toolchain)
        
        var configuration:String { "debug" }
        let path:(cache:AbsolutePath, build:AbsolutePath, product:AbsolutePath)
        path.cache      = workspace.appending(component: ".cache")
        path.build      = workspace.appending(component: ".build")
        path.product    = path.build.appending(component: configuration).appending(
            component: "\(triple.dynamicLibraryPrefix)\(dependency.product)\(triple.dynamicLibraryExtension)")
        
        let arguments:[String] = 
        [
            "swift", "build", "--product", dependency.product, 
            "-c", configuration, 
            "--package-path",   "\(dependency.path)", 
            "--cache-path",     "\(path.cache)", 
            "--build-path",     "\(path.build)", 
            "--disable-repository-cache",
            "-Xswiftc", "-DBUILD_STAGE_INERT"
        ]
        
        print("building inert framework with invocation:")
        print(arguments.joined(separator: " "))
        
        let process:Process = .init(arguments: arguments, environment: ProcessEnv.vars, 
            outputRedirection: .none)
        try process.launch()
        let result:ProcessResult = try process.waitUntilExit()
            
        guard case .terminated(code: 0) = result.exitStatus
        else 
        {
            fatalError("error: build stage 'inert' failed")
        }
        
        guard let library:DLHandle = try? dlopen("\(path.product)", mode: [.now, .local]) 
        else 
        {
            fatalError("failed to open incomplete library at '\(path.product)'")
        }
        
        guard let entrypoint:@convention(c) () -> UnsafeMutableRawPointer = 
            dlsym(library, symbol: Self.entrypoint) 
        else 
        {
            fatalError("missing symbol '\(Self.entrypoint)'")
        }
        
        guard let inspector:InspectorFunction = 
            Unmanaged<AnyObject>.fromOpaque(entrypoint()).takeRetainedValue() 
            as? InspectorFunction
        else 
        {
            fatalError("wrong inspector function signature")
        }
        
        // dlclose seems to be broken, so we leak the dynamic library, just as 
        // the swift official tools do: 
        // https://github.com/apple/swift-tools-support-core/blob/main/Sources/TSCUtility/IndexStore.swift#L264
        library.leak()
        
        return inspector()
    }
}

extension Synthesizer 
{
    static 
    func generate(staged:AbsolutePath, interface:[(typename:String, symbols:[String], signatures:[String])])
    {
        Source.generate(file: staged) 
        {
            """
            // generated by '\(#file)'
            
            import GDNative
            
            func <- <T>(property:Godot.NativeScriptInterface<T>.Witness.Property, symbol:String) 
                -> Godot.NativeScriptInterface<T>.Member
                where T:Godot.NativeScript
            {
                .property(witness: property, symbol: symbol)
            }
            func <- <T>(method:@escaping Godot.NativeScriptInterface<T>.Witness.Method, symbol:String) 
                -> Godot.NativeScriptInterface<T>.Member
                where T:Godot.NativeScript
            {
                .method(witness: method, symbol: symbol)
            }
            
            """
            for (typename, symbols, _):(String, [String], [String]) in interface 
            {
                let _ = print("generating 'Godot.NativeScript' conformance for type '\(typename)'")
                // if `instance` is a class, this will simply produce the class instance pointer. 
                // if `instance` is a struct, which does not fit in the protocol-typed object’s
                // inline storage, the struct will be copied to a new allocation, which is 
                // then referred to in a class. this is not efficient, so use of `struct`s in 
                // godot-facing interfaces is discouraged.
                //
                //            `class`                                `struct`
                //       user-data pointer                      user-data pointer 
                //                ↓                                      ↓
                //         instance data                          storage pointer
                //                                                       ↓
                //                                                instance data
            """
            extension \(typename)
            {
                static 
                func register(with api:Godot.API.NativeScript) 
                {
                    let initializer:Godot.API.NativeScript.Initializer = 
                    {
                        (
                            delegate:UnsafeMutableRawPointer?, 
                            metadata:UnsafeMutableRawPointer?
                        ) -> UnsafeMutableRawPointer? in 
                        
                        guard let delegate:UnsafeMutableRawPointer = delegate 
                        else 
                        {
                            fatalError("(swift) \(typename).init(delegate:) received nil delegate pointer")
                        }
                        
                        #if ENABLE_ARC_SANITIZER
                        guard let metadata:UnsafeMutableRawPointer = metadata 
                        else 
                        {
                            fatalError("(swift) \(typename).init(delegate:) received nil metadata pointer")
                        }
                        
                        Unmanaged<\(typename).Interface.Metatype.Symbol>
                            .fromOpaque(metadata)
                            .takeUnretainedValue()
                            .track()
                        #endif
                        
                        return Unmanaged<AnyObject>.passRetained(
                            \(typename).init(delegate: .init(delegate)) as AnyObject).toOpaque() 
                    }
                    let deinitializer:Godot.API.NativeScript.Deinitializer =
                    {
                        (
                            delegate:UnsafeMutableRawPointer?, 
                            metadata:UnsafeMutableRawPointer?, 
                            instance:UnsafeMutableRawPointer?
                        ) in
                        
                        guard let instance:UnsafeMutableRawPointer = instance 
                        else 
                        {
                            fatalError("(swift) `\(typename).deinit` received nil instance pointer")
                        }
                        
                        #if ENABLE_ARC_SANITIZER
                        guard let metadata:UnsafeMutableRawPointer = metadata 
                        else 
                        {
                            fatalError("(swift) \(typename).deinit received nil metadata pointer")
                        }
                        
                        Unmanaged<\(typename).Interface.Metatype.Symbol>
                            .fromOpaque(metadata)
                            .takeUnretainedValue()
                            .untrack()
                        #endif
                        
                        Unmanaged<AnyObject>.fromOpaque(instance).release()
                    }
                    let dispatch:Godot.API.NativeScript.Method = 
                    {
                        (
                            delegate:UnsafeMutableRawPointer?, 
                            metadata:UnsafeMutableRawPointer?, 
                            instance:UnsafeMutableRawPointer?, 
                            count:Int32, 
                            arguments:UnsafeMutablePointer<UnsafeMutablePointer<godot_variant>?>?
                        ) -> godot_variant in 
                        
                        let index:Int   = .init(bitPattern: metadata)
                        let name:String = \(typename).interface[method: index].symbol
                        // unretained because godot retained `self` in the initializer call
                        guard   let instance:UnsafeMutableRawPointer = instance, 
                                let self:\(typename) = 
                                Unmanaged<AnyObject>.fromOpaque(instance).takeUnretainedValue() as? \(typename) 
                        else 
                        {
                            fatalError("(swift) \(typename).\\(name)(delegate:arguments:) received nil or invalid instance pointer")
                        }
                        
                        guard   let delegate:UnsafeMutableRawPointer = delegate 
                        else 
                        {
                            fatalError("(swift) \(typename).\\(name)(delegate:arguments:) received nil delegate pointer")
                        }
                        
                        let variants:[Godot.Variant?]
                        if let arguments:UnsafeMutablePointer<UnsafeMutablePointer<godot_variant>?> = arguments 
                        {
                            variants = (0 ..< .init(count)).map 
                            {
                                guard let pointer:UnsafeMutablePointer<godot_variant> = arguments[$0]
                                else 
                                {
                                    fatalError("(swift) \(typename).\\(name)(delegate:arguments:) received nil argument pointer")
                                }
                                
                                return .pass(retained: pointer)
                            }
                        }
                        else 
                        {
                            variants = []
                        }
                        
                        return Godot.Variant.take(unretained: 
                            \(typename).interface[method: index].witness(self)(.init(delegate), variants))
                    }
                    
                    let symbols:[String] = [\(symbols.map{ "\"\($0)\"" }.joined(separator: ", "))]
                    
                    #if ENABLE_ARC_SANITIZER
                    let sanitizer:Godot.API.NativeScript.WitnessDeinitializer = 
                    {
                        (metadata:UnsafeMutableRawPointer?) in 
                        
                        guard let metadata:UnsafeMutableRawPointer = metadata 
                        else 
                        {
                            fatalError("(swift) \(typename).sanitizer received nil metadata pointer")
                        }
                        
                        Unmanaged<\(typename).Interface.Metatype.Symbol>
                            .fromOpaque(metadata)
                            .release()
                    }
                    
                    let metatype:\(typename).Interface.Metatype = .init(symbols: symbols)
                    
                    #else 
                    let sanitizer:Godot.API.NativeScript.WitnessDeinitializer? = nil
                    #endif
                    
                    for symbol:String in symbols
                    {
                        // register type 
                        #if ENABLE_ARC_SANITIZER
                        let metadata:UnsafeMutableRawPointer  = 
                            Unmanaged<\(typename).Interface.Metatype.Symbol>
                            .passRetained(.init(symbol, metatype: metatype))
                            .toOpaque()
                        #else 
                        let metadata:UnsafeMutableRawPointer? = nil
                        #endif
                        
                        let constructor:godot_instance_create_func = .init(
                            create_func:    initializer, method_data: metadata, free_func: sanitizer)
                        let destructor:godot_instance_destroy_func = .init(
                            destroy_func: deinitializer, method_data: metadata, free_func: nil)
                        
                        api.register(initializer: constructor, deinitializer: destructor, 
                            for: Self.self, as: symbol)
                        
                        // register methods 
                        for index:Int in Self.interface.methods.indices  
                        {
                            let method:godot_instance_method = .init(
                                method:         dispatch, 
                                method_data:   .init(bitPattern: index), 
                                free_func:      nil)
                            
                            api.register(method: method, 
                                as: (type: symbol, method: Self.interface[method: index].symbol)) 
                        }
                    }
                }
            }
            """
            }
        }
    }
}

#endif
